#!/usr/bin/env bash

SCRIPT_DIR="${HOME}/.scripts/site-control"

# Decoration ----------------------------------------------------------------------------
R='\033[0;31m'
G='\033[0;32m'
Y='\033[0;33m'
B='\033[0;34m'
M='\033[0;35m'
C='\033[0;36m'
NC='\033[0m'

banner() { printf "${M}============ ${B}%s ${M}============${NC} %s\n" "$1" "${2:+\n$2}"; }

ERR() { echo -e "${R}✗${NC} $1" >&2; }
OK() { echo -e "${G}✓${NC} $1"; }
WARN() { echo -e "${Y}WARNING: $1${NC}" >&2; }
TODO() { echo -e "${Y}TODO: ${C}$1${NC}" >&2; }
DEBUG() { echo -e "${Y}DEBUG:${NC} $1" >&2; }

# Initialization -------------------------------------------------------------------------
script_init() {
    if [ -f "$MAIN_CFG" ]; then
        return 0;
    fi
    MAIN_CFG="${SCRIPT_DIR}/site-control-config.yaml"
    if [[ ! -f "$MAIN_CFG" ]]; then
        ERR "Config file not found: $MAIN_CFG"
        echo "Script will exit, rebuild global config and re-run."
        return 1
    fi
    if ! CFG_KEYS=$(yq e '.sites | keys[] | .' "$MAIN_CFG" 2>/dev/null); then
        WARN "No existing sites found on init."
    fi
}
script_init

# Helpers -------------------------------------------------------------------------------
has_local_config() {
    if [ -f "${PWD}/cfg.yaml" ]; then
        return 0;
    fi
    return 1;
}

has_script_config() {
    if [ -f "${MAIN_CFG}" ]; then
        return 0;
    fi
    return 1;
}

get_version_info() {
    local path="$1"
    local current_branch; current_branch=$(
        git -C "$path" branch --show-current 2>/dev/null || echo "unknown"
    )
    local prod_version; prod_version=$(
        git -C "$path" describe --abbrev=0 2>/dev/null || echo "unknown"
    )
    local dev_version; dev_version=$(
        git -C "$path" tag --sort=-version:refname | head -1 2>/dev/null || echo "unknown"
    )
    local commits; commits=$(
        git -C "$path" rev-list --count main..HEAD 2>/dev/null || echo "0"
    )
    echo "$prod_version|$dev_version|$commits|$current_branch"
}

update_version_info() {
    local site="$1"   
    local path; if ! path=$(yq e ".sites.${site}.root" "$MAIN_CFG"); then
        ERR "Updating version info failed: site root path not found"
    fi

    local vinfo; vinfo=$(get_version_info "$path")
    local vprod; vprod=$(echo "$vinfo" | cut -d'|' -f1)
    local vdev; vdev=$(echo "$vinfo" | cut -d'|' -f2)
    local commits; commits=$(echo "$vinfo" | cut -d'|' -f3)
    local branch; branch=$(echo "$vinfo" | cut -d'|' -f4)
    yq -i "with(.sites.${site};
        .dev_version = \"${vdev}\" |
        .prod_version = \"${vprod}\" |
        .commit_diff = ${commits} |
        .dev_branch = \"${branch}\"
    )" "${MAIN_CFG}"
}

# YAML ----------------------------------------------------------------------------------
get_and_incr_site_count() {
    local site_count=$((1 + $(yq e '.global.site_count' "$MAIN_CFG")))
    yq -i ".global.site_count = $site_count" "$MAIN_CFG"
    echo $site_count
}

make_local_config() {
    local site="$1"
    local local_cfg; local_cfg="${PWD}/cfg.yaml"
    touch "$local_cfg"
    read -r -p "Enter site description: " \
        -i "Webapp to log and view fuel economy data" -e desc
    read -r -p "Enter repo URL: " \
        -i "http://github.com/theHousedev/fuel-log" -e git_url
    yq -i "with(.site;
        .tag = \"${site}\" |
        .name = \"${site^} Log\" |
        .description = \"${desc}\" |
        .git_repo = \"${git_url}\"
    )" "${local_cfg}"
    OK "Created local config file: $local_cfg"
}

register() {
    local site="$1"
    local index; index=$(get_and_incr_site_count)
    local bbase; bbase=$(yq e '.global.base_bport' "$MAIN_CFG")
    local fbase; fbase=$(yq e '.global.base_fport' "$MAIN_CFG")
    local rootdir; rootdir=${PWD}

    yq -i "with(.sites.${site};
        .index = ${index} |
        .tag = \"${site}\" |
        .name = \"${site^} Log\" |
        .status = \"stopped\" |
        .fport = $((index + fbase)) |
        .bport = $((index + bbase)) |
        .root = \"${rootdir}\" |
        .fdir = \"${rootdir}/app\" |
        .bdir = \"${rootdir}/backend\" |
        .config = \"${rootdir}/cfg.yaml\" |
        .last_start = null |
        .last_deploy = null
    )" "${MAIN_CFG}"

    update_version_info "$site"
}

# Core Functions ------------------------------------------------------------------------
z() { # tester function == != >= <= // ~
    update_version_info "$1"
}

list() {
    TODO "list"
}

new() {
    local site="$1"
    if has_local_config; then
        ERR "Local config already exists"
        echo -e "Use '${G}site stats $site${NC}' to view details.\n" >&2;
        return 1;
    else
        if [ "$site" != "${PWD##*/}" ]; then
            ERR "'$site' is invalid - must match present dir name."
            read -nr 1 -p "  Proceed using pwd name '${PWD##*/}'? (y/n) " proceed
            echo ""
            case "$proceed" in
                y|Y|yes|YES) site="${PWD##*/}" ;;
                n|N|no|NO) echo -e "Quitting setup."; return 1; ;;
                *) echo -e "Invalid response, quitting setup."; return 1; ;;
            esac
        fi

        echo -e "Configuring '$site'..."
        if ! make_local_config "$site"; then
            ERR "Failed to create local config; aborting..."
            exit 1
        fi

        if ! register "$site"; then
            ERR "Failed to register site, aborting..."
            exit 1
        else
            OK "Successfully registered site"
        fi
    fi
}

dev() {
    local site="$1"
    
    # check if dir (& subdirs) exist

    # check for .env file
    
    # check for existing tmux dev session

    # check for existing prod session; stop gracefully if found
    
    # start site in dev mode
    echo "  Starting local dev server..."

    # print success: details, localhost url, etc.

    # print "tmux a SITE:${SITE_TRUNK[$1]}" as final line
}

deploy() {
    TODO "deploy"
}

push() {
    TODO "push"
}

stats() {
    for site in "$CFG_KEYS"; do
        echo "$site"
    done
}

logs() {
    TODO "logs"
}

help() {
    if [ "$1" == "short" ]; then
        echo -e "\nUsage: ${G}site <command> <site>${NC}"
        echo -e "Show all commands: '${G}site -h${NC}'\n"
        return 0;
    fi
    banner "Site Control Help"
    echo -e "Usage: ${G}site <command> <site>${NC}"
    echo -e "\nCommands:"
    echo -e "  ${G}help${NC}            Show this help message"
    echo -e "  ${G}list${NC}            List all sites"
    echo -e "  ${G}new <site>${NC}      Initialize a new site"
    echo -e "  ${G}dev <site>${NC}      Start a site in dev mode"
    echo -e "  ${G}deploy <site>${NC}   Deploy a live site"
    echo -e "  ${G}push <site>${NC}     Push a site to prod"
    echo -e "  ${G}stats <site>${NC}    Show stats for one (or all) sites"
    echo -e "  ${G}logs <site>${NC}     Show logs for one (or all) sites"
}

# main -----------------------------------------------------------------------------
main() {
    case "${1}" in
        new) new "$2";; list) list ;; -h|--help|help) help ;;
        dev) dev "$2" ;; deploy) deploy "$2" ;; push) push "$2";;
        stats) stats "$2" ;; logs) logs ;; z) z "$2";; *) help "short" ;;
    esac
}

main "$@"
